### ISSUE TITLE
Configure accounts

### ISSUE THREAD

**Issue by gabrielmedina** [gabrielmedina/coach#1]
This task is intended for basic configuration of the accounts package.
### Task list
- [x] Configure packager accounts.
- [x] Add user profile (name, type, status).
- [x] Add template userProfile.
- [x] Add treatment response messages.
